### ISSUE TITLE
Axios Invalid URL

### ISSUE THREAD

**Issue by renliangxa** [metrico/gigapipe#543]
{"level":50,"time":1723100479595,"pid":6196,"hostname":"DESKTOP-B4HCQ71","name":"qryn","msg":"rawRequest error: CREATE DATABASE IF NOT EXISTS qryn "}
{"level":50,"time":1723100479597,"pid":6196,"hostname":"DESKTOP-B4HCQ71","name":"qryn","err":"Invalid URL\nTypeError: Invalid URL\n    at new URL (node:internal/url:775:36)\n    at dispatchHttpRequest (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:2701:20)\n    at D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:2621:5\n    at new Promise (<anonymous>)\n    at wrapAsync (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:2601:10)\n    at http (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:2639:10)\n    at Axios.dispatchRequest (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:3622:10)\n    at Axios._request (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:4001:33)\n    at Axios.request (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:3871:25)\n    at wrap (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:28:15)\n    at Axios.request (D:\\workspace\\qryn\\node_modules\\axios\\dist\\node\\axios.cjs:3876:41)\n    at async Object.rawRequest (D:\\workspace\\qryn\\lib\\db\\clickhouse.js:1386:12)\n    at async upgradeRequest (D:\\workspace\\qryn\\lib\\db\\maintain\\index.js:88:3)\n    at async upgradeSingle (D:\\workspace\\qryn\\lib\\db\\maintain\\index.js:49:5)\n    at async module.exports.upgrade (D:\\workspace\\qryn\\lib\\db\\maintain\\index.js:21:3)\n    at async initialize (D:\\workspace\\qryn\\lib\\db\\clickhouse.js:191:5)\n    at async D:\\workspace\\qryn\\qryn_node.js:75:5","msg":"Error starting qryn"}

**Comment by lmangani** [comment]
> Invalid URL

@renliangxa hard to understand the report without knowing the config or any details. Could you document the issue further?

**Comment by renliangxa** [comment]
### Environment
- OS windows
- axios 1.6.8
![image](https://github.com/user-attachments/assets/4efe25cd-ef1b-4f69-aa35-58db018ed920)

**Comment by renliangxa** [comment]
fix:
- clickhouse url delete clickhouseOptions.auth

![image](https://github.com/user-attachments/assets/59f25013-b973-4865-816b-01d0c9286197)

- request header add Basic Authorization param

![image](https://github.com/user-attachments/assets/fe5797cc-c0fc-4196-b767-c23ccc5e8168)

- To modify other axios calls to include Authorization  header param

**Comment by lmangani** [comment]
I'm not sure I understand this report. If this is a change request, please feel free to submit a PR 👍
